mysite-master/mysite/mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.decorators.cache import never_cache
from django.views.static import serve
from django.views.generic import RedirectView


urlpatterns = [
    path('polls/', include('polls.urls')),
    path('', RedirectView.as_view(url='/polls/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite-master/mysite/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('register/', views.RegisterUserView.as_view(), name='register'),
    path('delete/', views.DeleteUserView.as_view(), name='profile_delete'),
    path('change/', views.ChangeUserInfoView.as_view(), name='profile_change'),
]

mysite-master/mysite/polls/models.py
import datetime
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator, FileExtensionValidator
from django.db import models
from django.dispatch import Signal
from django.urls import reverse
from django.utils import timezone
from django.utils.crypto import get_random_string


def get_name_file(instance, filename):
    return 'mysite/file'.join([get_random_string(5) + '_' + filename])


class Question(models.Model):
    question_text = models.CharField(max_length=200, verbose_name='Название опроса')
    pub_date = models.DateTimeField('date published')
    description_question = models.CharField(max_length=200, verbose_name='Краткое описание')
    description_choice = models.CharField(max_length=200, verbose_name='Подробное описание')
    img = models.ImageField(max_length=200, verbose_name='Картинка', upload_to=get_name_file, blank=True, null=True,
                            validators=[FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])


    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.question_text

    def get_absolute_url(self):
        return reverse('detail', args=[str(self.id)])


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200, blank=False)
    votes = models.IntegerField(default=0)


    def __str__(self):
        return self.choice_text


class Vote(models.Model):
    voter = models.ForeignKey('User', verbose_name='Пользователь', related_name='+', on_delete=models.CASCADE)
    question_vote = models.ForeignKey(Question, verbose_name='Опрос', on_delete=models.CASCADE)


class User(AbstractUser):
    name = models.CharField(max_length=200, verbose_name='Имя', blank=False, validators=[
        RegexValidator(
            regex='^[А-Яа-я -]*$',
            message='Имя пользователя должно состоять из кириллицы',
            code='invalid_username'
        ),
    ])
    surname = models.CharField(max_length=200, verbose_name='Фамилия', blank=False, validators=[
        RegexValidator(
            regex='^[А-Яа-я -]*$',
            message='Фамилия пользователя должно состоять из кириллицы',
            code='invalid_username'
        ),
    ])
    username = models.CharField(max_length=200, verbose_name='Логин', unique=True, blank=False, validators=[
        RegexValidator(
            regex='^[A-Za-z -]*$',
            message='Имя пользователя должно состоять только из латиницы',
            code='invalid_username'
        ),
    ])
    avatar = models.ImageField(max_length=200, upload_to=get_name_file, verbose_name='Аватар', blank=False,
                               null=True,
                               validators=[FileExtensionValidator(
                                   allowed_extensions=['png', 'jpg', 'jpeg'])])
    email = models.EmailField(max_length=200, verbose_name='Почта', unique=True, blank=False)
    password = models.CharField(max_length=200, verbose_name='Пароль', blank=False)

    USERNAME_FIELD = 'username'

    def __str__(self):
        return str(self.name) + ' ' + str(self.surname)

    class Meta:
        ordering = ['name']


user_registrated = Signal()

mysite-master/mysite/polls/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import BaseInlineFormSet

from .models import User, Choice
from .models import user_registrated


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True,
                             label='Адрес электронной почты')
    password1 = forms.CharField(label='Пароль',
                                widget=forms.PasswordInput, )
    password2 = forms.CharField(label='Пароль (повторно)',
                                widget=forms.PasswordInput,
                                help_text='Повторите тот же самый пароль еще раз')

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError(
                'Введенные пароли не совпадают', code='password_mismatch'
            )}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=True)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = True
        if commit:
            user.save()
        user_registrated.send(RegisterUserForm, instance=user)
        return user

    class Meta:
        model = User
        fields = ('name', 'surname', 'username', 'email', 'avatar')


class ChangeUserInfoForm(forms.ModelForm):
    email = forms.EmailField(required=True,
                             label='Адрес электронной почты')

    class Meta:
        model = User
        fields = ('name', 'surname', 'username', 'email', 'avatar')


class RequiredInlineFormSet(BaseInlineFormSet):
    def _construct_form(self, i, **kwargs):
        form = super(RequiredInlineFormSet, self)._construct_form(1, **kwargs)
        form.empty_permitted = False
        return form

mysite-master/mysite/polls/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.db.models import Count
from django.db.models.functions import datetime
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Question, Choice, User, Vote
from django.urls import reverse
from django.views import generic
from .forms import RegisterUserForm
from django.views.generic import UpdateView, CreateView, DeleteView
from django.contrib.auth import logout
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from .forms import ChangeUserInfoForm


class IndexView(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


@login_required
def vote(request, question_id):
    question_vote = get_object_or_404(Question, pk=question_id)
    vote, created = Vote.objects.get_or_create(voter=request.user, question_vote=question_vote)
    if not created:
        return render(request, 'polls/detail.html', {
            'question': question_vote,
            'error_message': 'Голосовать можно только один раз'
        })
    try:
        selected_choice = question_vote.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question_vote,
            'error_message': 'Вы не сделали выбор'
        })

    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question_vote.id,)))


class StudioLoginView(LoginView):
    template_name = 'registrations/login.html'


class StudioLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'registrations/login.html'


class RegisterUserView(CreateView):
    model = User
    template_name = 'registration/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('polls:index')


class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = User
    template_name = 'registration/delete_user.html'
    success_url = reverse_lazy('polls:index')

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS, 'Пользователь удален')
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin,
                         UpdateView):
    model = User
    template_name = 'registration/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy('polls:profile')
    success_message = 'Личные данные пользователя изменены'

    def dispatch(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().dispatch(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)

mysite-master/mysite/polls/templates/base.html
{% load static %}
{% load bootstrap4 %}
{% load thumbnail %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='slim' %}
    <title>{% block title %} Главная {% endblock %} - Опросы </title>
</head>
<body>
<div class="container-fluid">
    <div class="d-flex flex-column flex-md-row p-3 px-md-4 mb-3  bg-white border-bottom box-shadow">
        <h5 class="mr-md-auto p-2">Опросы</h5>
        <div class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true"
               aria-expanded="false">Профиль</a>
            <div class="dropdown-menu">
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'polls:profile_change' %}">Изменить личные данные</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'logout' %}">Выйти</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'polls:profile_delete' %}">Удалить</a>
            </div>
        </div>
        {% if not user.is_authenticated %}
        <a class="p-2 text-dark" href="{% url 'polls:register' %}">Регистрация</a>
        <a class="p-2 text-dark" href="{% url 'login' %}">Вход</a>
        {% endif %}
    </div>
    <div class="row">

        <nav class="col-md-auto nav flex-column">
            <a class="nav-link root" href="{% url 'polls:index'  %}">Главная</a>
            <span class="nav-link root font-weight-bold">
               Пользователь: {{ user.get_username }} <img src="{% thumbnail user.avatar 'default' %}">
           </span>
        </nav>

        <div class="container">
            {% bootstrap_messages %}
            {% block content %}
            {% endblock %}
        </div>

    </div>

    <footer class="mt-3 border-top">

    </footer>
</div>

</body>
</html>

mysite-master/mysite/polls/templates/index.html
{% extends "base.html" %}
{% block content %}
{% if not user.is_staff%}
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    {% if question.was_published_recently %}
    <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a>&emsp;
        {{question.description_question}}
    </li>
    {% endif %}
    {% endfor %}
</ul>
{% else %}
<p>
    Нет вопросов!
</p>
{% endif %}
{% endif %}
{% if user.is_staff%}
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}

    <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a>&emsp;
        {{question.description_question}}
    </li>

    {% endfor %}
</ul>
{% else %}
<p>
    Нет вопросов!
</p>
{% endif %}
{% endif %}
{% endblock %}